#!/bin/bash
cd ..
source Configuration
source bin/activate

DEBUG=False
export DEBUG
TEST_MODE=True
export TEST_MODE
APP_PREFIX=''
export APP_PREFIX

cd pwi/tests

echo 'Running acceptance tests in Postgres mode'

python all_tests.py
if [ $? -ne 0 ]; then
        exit 1
fi

