#!/bin/bash
cd ..
source Configuration
source bin/activate

DEBUG=False
export DEBUG

cd internalwi/tests

echo 'Running acceptance tests in Postgres mode'
DBTYPE=Postgres
export DBTYPE

python tests.py

echo 'Running acceptance tests in Sybase mode'
DBTYPE=Sybase
export DBTYPE

python tests.py
