#!/bin/bash
cd ..
source Configuration
source bin/activate

DEBUG=False
export DEBUG
TEST_MODE=True
export TEST_MODE

cd pwi/tests

echo 'Running acceptance tests in Postgres mode'
DBTYPE=Postgres
export DBTYPE

python all_tests.py
if [ $? -ne 0 ]; then
        exit 1
fi

echo 'Running acceptance tests in Sybase mode'
DBTYPE=Sybase
export DBTYPE

python all_tests.py
if [ $? -ne 0 ]; then
        exit 1
fi
